// Production configuration for Render deployment
export const productionConfig = {
  // Database will be automatically configured via DATABASE_URL
  database: {
    url: process.env.DATABASE_URL,
  },
  
  // JWT secrets will be auto-generated by Render
  jwt: {
    accessSecret: process.env.JWT_ACCESS_SECRET,
    refreshSecret: process.env.JWT_REFRESH_SECRET,
  },
  
  // Server configuration
  server: {
    port: process.env.PORT || 10000,
    host: '0.0.0.0', // Required for Render
  },
  
  // CORS configuration for production
  cors: {
    origin: [
      process.env.FRONTEND_URL || 'https://swimflow-frontend.onrender.com',
      /\.onrender\.com$/, // Allow all Render subdomains
    ],
    credentials: true,
  },
  
  // Security settings for production
  security: {
    rateLimitWindowMs: 15 * 60 * 1000, // 15 minutes
    rateLimitMax: 100, // requests per window
  },
}